import { describe, it, expect } from 'vitest';
import { readFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';
import {
  documentBody,
  documentVersion,
  LEGAL_DOCUMENT_IDS,
  READABLE_DOCUMENT_IDS,
  REFERENCE_DOCUMENT_IDS,
} from './documents';

/**
 * `docs/legal/` is the source of truth; `./documents/` holds copies the bundler
 * can reach. This is the guard that keeps them the same document — without it a
 * user could accept version `x` while being shown text that no longer says `x`.
 */

// Vitest does provide __dirname, but import.meta.url is the ESM-native form
// and does not depend on that interop staying in place.
const HERE = dirname(fileURLToPath(import.meta.url));
const SOURCE_DIR = join(HERE, '../../../../docs/legal');

const FILENAMES: Record<string, string> = {
  linkedin_risk_disclosure: 'LINKEDIN_RISK_DISCLOSURE.md',
  terms_of_use: 'TERMS_OF_USE.md',
  privacy_policy: 'PRIVACY_POLICY.md',
  acceptable_use: 'ACCEPTABLE_USE.md',
  data_retention: 'DATA_RETENTION.md',
};

/** Every `.md` filename the bundle ships, i.e. everything a reader can open. */
const BUNDLED_FILENAMES = READABLE_DOCUMENT_IDS.map((id) => FILENAMES[id]);

describe('legal document sync', () => {
  it.each(READABLE_DOCUMENT_IDS)('%s matches docs/legal/', (id) => {
    const source = readFileSync(join(SOURCE_DIR, FILENAMES[id]), 'utf8');
    const bundled = readFileSync(join(HERE, 'documents', FILENAMES[id]), 'utf8');

    // The copy carries a generated-file banner; the rest must be identical.
    expect(bundled.replace(/^<!-- Generated by[^\n]*\n/, '')).toBe(source);
  });

  it.each(READABLE_DOCUMENT_IDS)('%s declares a version', (id) => {
    expect(documentVersion(id)).toMatch(/^\d{4}-\d{2}-\d{2}\.\d+$/);
  });

  it('keeps the reference documents out of the acceptance set', () => {
    // DATA_RETENTION is readable but not acknowledgment-gated. If it ever
    // reached LEGAL_DOCUMENT_IDS it would have to appear in the backend's
    // REQUIRED_DOCUMENTS too, and every user would be re-prompted.
    expect(LEGAL_DOCUMENT_IDS).toEqual([
      'linkedin_risk_disclosure',
      'terms_of_use',
      'privacy_policy',
      'acceptable_use',
    ]);
    expect(REFERENCE_DOCUMENT_IDS).toEqual(['data_retention']);
    for (const id of REFERENCE_DOCUMENT_IDS) {
      expect(LEGAL_DOCUMENT_IDS).not.toContain(id);
    }
  });

  it('shows the reader no link they cannot follow', () => {
    // documentBody strips relative link syntax down to its text, so nothing
    // 404s. What it cannot fix is prose that names a document the bundle does
    // not carry: before DATA_RETENTION.md was synced, the privacy policy's
    // entire "How long we keep it" section was the sentence "See
    // DATA_RETENTION.md" — a file the reader had no way to open.
    for (const id of READABLE_DOCUMENT_IDS) {
      const body = documentBody(id);

      const relativeLinks = (body.match(/\[[^\]]+\]\([^)]*\)/g) ?? []).filter(
        (link) => !/\]\(\s*https?:/.test(link)
      );
      expect(relativeLinks, `${id} renders a relative link`).toEqual([]);

      const namedFiles = body.match(/[A-Z_]+\.md/g) ?? [];
      for (const filename of namedFiles) {
        expect(BUNDLED_FILENAMES, `${id} names unbundled ${filename}`).toContain(filename);
      }
    }
  });

  it('strips internal TODO comments from what users see', () => {
    // These hold notes for counsel — missing abuse addresses, unresolved
    // questions. A user reading a policy in an acceptance dialog must not see
    // them, and must not see a heading that promises a section we removed.
    for (const id of READABLE_DOCUMENT_IDS) {
      const body = documentBody(id);
      expect(body).not.toContain('TODO');
      expect(body).not.toContain('<!--');
    }
    expect(documentBody('acceptable_use')).not.toContain('## Reporting');
    expect(documentBody('acceptable_use')).not.toContain('abuse@');
  });

  it('strips the internal draft banner from what users see', () => {
    // The "NOT REVIEWED BY A LAWYER" note is for us, not for someone being
    // asked to accept the document.
    for (const id of READABLE_DOCUMENT_IDS) {
      expect(documentBody(id)).not.toContain('NOT LEGAL ADVICE');
      expect(documentBody(id)).not.toContain('DRAFT');
    }
  });

  it('keeps the substance after stripping', () => {
    const body = documentBody('linkedin_risk_disclosure');

    expect(body).toContain('permanently banned');
    expect(body).toContain('two-factor');
    expect(body.length).toBeGreaterThan(2000);
  });

  it('shows the risk disclosure without asserting a breach', () => {
    // The published position is factual risk, not an admission — see
    // docs/legal/README.md.
    const body = documentBody('linkedin_risk_disclosure').toLowerCase();

    expect(body).not.toContain('breaches linkedin');
    expect(body).not.toContain('in breach of linkedin');
  });
});
