AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: WarmReach Backend - SAM Template with RAGStack Integration

Parameters:
  Environment:
    Type: String
    Default: prod
    AllowedValues:
      - dev
      - prod
  IncludeDevOrigins:
    Type: String
    Default: 'true'
    AllowedValues:
      - 'true'
      - 'false'
  ProductionOrigins:
    Type: String
    Default: ''
    Description: Comma-separated production origins for CORS (Lambda env vars)
  ProductionOrigin:
    Type: String
    Default: ''
    Description: Primary production origin for S3 CORS (e.g., https://myapp.com)
  OpenAIApiKey:
    Type: String
    Default: ''
    NoEcho: true
    Description: OpenAI API key for LLM Lambda
  BedrockModelId:
    Type: String
    Default: us.meta.llama3-2-90b-instruct-v1:0
    Description: Bedrock model ID for LLM operations
  # RAGStack Integration - Nested Stack (recommended)
  DeployRAGStack:
    Type: String
    Default: 'true'
    AllowedValues:
      - 'true'
      - 'false'
    Description: Deploy RAGStack as nested stack (true) or use external endpoint (false)
  AdminEmail:
    Type: String
    Default: ''
    Description: Admin email for RAGStack deployment (required if DeployRAGStack=true)
    AllowedPattern: '^([\w.+-]+@([\w-]+\.)+[\w-]{2,6})?$'
  # RAGStack Integration - External Endpoint (alternative to nested deployment)
  RagstackGraphqlEndpoint:
    Type: String
    Default: ''
    Description: External RAGStack GraphQL endpoint (used only if DeployRAGStack=false)
  RagstackApiKey:
    Type: String
    Default: ''
    NoEcho: true
    Description: External RAGStack API key (used only if DeployRAGStack=false)

Rules:
  AdminEmailRequiredForRAGStack:
    RuleCondition: !Equals [!Ref DeployRAGStack, 'true']
    Assertions:
      - Assert: !Not [!Equals [!Ref AdminEmail, '']]
        AssertDescription: AdminEmail is required when DeployRAGStack is true

Globals:
  Function:
    Runtime: python3.13
    Timeout: 30
    MemorySize: 512
    Layers:
      - !Ref SharedPythonLayer
    Environment:
      Variables:
        DYNAMODB_TABLE_NAME: !Ref ProfilesTable
        LOG_LEVEL: INFO
        ALLOWED_ORIGINS: !If
          - IncludeDevOriginsCondition
          - !Sub 'http://localhost:5173,http://localhost:3000${ProductionOrigins}'
          - !Ref ProductionOrigins

Conditions:
  IncludeDevOriginsCondition: !Equals [!Ref IncludeDevOrigins, 'true']
  HasProductionOrigin: !Not [!Equals [!Ref ProductionOrigin, '']]
  DeployRAGStackCondition: !Equals [!Ref DeployRAGStack, 'true']

Resources:
  # Shared Python Layer for common code (errors, utils, services)
  SharedPythonLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub 'warmreach-shared-python-${Environment}'
      Description: Shared Python utilities for WarmReach Lambdas
      ContentUri: lambdas/shared/
      CompatibleRuntimes:
        - python3.13
      RetentionPolicy: Delete

  # RAGStack-Lambda Nested Stack for semantic search and profile ingestion
  RAGStackNestedStack:
    Type: AWS::CloudFormation::Stack
    Condition: DeployRAGStackCondition
    Properties:
      TemplateURL: https://ragstack-quicklaunch-public-631094035453.s3.us-east-1.amazonaws.com/ragstack-template.yaml
      Parameters:
        StackPrefix: !Sub '${AWS::StackName}-ragstack'
        AdminEmail: !Ref AdminEmail
        BuildDashboard: 'true'
        BuildWebComponent: 'true'
      TimeoutInMinutes: 60
      Tags:
        - Key: Application
          Value: warmreach
        - Key: Environment
          Value: !Ref Environment

  ProfilesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'warmreach-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: GSI1PK
          AttributeType: S
        - AttributeName: GSI1SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: GSI1PK
              KeyType: HASH
            - AttributeName: GSI1SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub 'warmreach-${Environment}'
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
          RequireUppercase: true

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub 'warmreach-client-${Environment}'
      UserPoolId: !Ref UserPool
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      GenerateSecret: false
      TokenValidityUnits:
        AccessToken: hours
        IdToken: hours
        RefreshToken: days
      AccessTokenValidity: 4
      IdTokenValidity: 4
      RefreshTokenValidity: 30

  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref Environment
      CorsConfiguration:
        AllowOrigins: !If
          - HasProductionOrigin
          - !If
            - IncludeDevOriginsCondition
            - - http://localhost:5173
              - http://localhost:3000
              - !Ref ProductionOrigin
            - - !Ref ProductionOrigin
          - - http://localhost:5173
            - http://localhost:3000
        AllowHeaders:
          - Content-Type
          - Authorization
          - X-Amz-Date
          - X-Api-Key
          - X-Amz-Security-Token
        AllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        AllowCredentials: true
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            IdentitySource: $request.header.Authorization
            JwtConfiguration:
              issuer: !Sub 'https://cognito-idp.${AWS::Region}.amazonaws.com/${UserPool}'
              audience:
                - !Ref UserPoolClient
      DefaultRouteSettings:
        ThrottlingBurstLimit: 10
        ThrottlingRateLimit: 5

  # ==========================================================================
  # WebSocket API for real-time client-backend communication
  # ==========================================================================
  WebSocketApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Sub 'warmreach-websocket-${Environment}'
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: $request.body.action

  WebSocketStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref WebSocketApi
      StageName: !Ref Environment
      AutoDeploy: true

  # IAM role for Lambdas to call @connections management API
  WebSocketManageConnectionsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'warmreach-ws-manage-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: ManageConnections
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - execute-api:ManageConnections
                Resource: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebSocketApi}/${Environment}/*'
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                  - dynamodb:DeleteItem
                  - dynamodb:Query
                Resource:
                  - !GetAtt ProfilesTable.Arn
                  - !Sub '${ProfilesTable.Arn}/index/*'

  # --- WebSocket Connect ---
  WebSocketConnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'warmreach-ws-connect-${Environment}'
      CodeUri: lambdas/websocket-connect/
      Handler: lambda_function.lambda_handler
      Timeout: 10
      Role: !GetAtt WebSocketManageConnectionsRole.Arn
      Layers:
        - !Ref SharedPythonLayer
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref ProfilesTable
          LOG_LEVEL: INFO
          COGNITO_USER_POOL_ID: !Ref UserPool
          COGNITO_REGION: !Ref AWS::Region
          WEBSOCKET_ENDPOINT: !Sub 'https://${WebSocketApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}'

  WebSocketConnectPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref WebSocketConnectFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebSocketApi}/*/$connect'

  WebSocketConnectIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebSocketConnectFunction.Arn}/invocations'

  WebSocketConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApi
      RouteKey: $connect
      AuthorizationType: NONE
      Target: !Sub 'integrations/${WebSocketConnectIntegration}'

  # --- WebSocket Disconnect ---
  WebSocketDisconnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'warmreach-ws-disconnect-${Environment}'
      CodeUri: lambdas/websocket-disconnect/
      Handler: lambda_function.lambda_handler
      Timeout: 10
      Role: !GetAtt WebSocketManageConnectionsRole.Arn
      Layers:
        - !Ref SharedPythonLayer
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref ProfilesTable
          LOG_LEVEL: INFO

  WebSocketDisconnectPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref WebSocketDisconnectFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebSocketApi}/*/$disconnect'

  WebSocketDisconnectIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebSocketDisconnectFunction.Arn}/invocations'

  WebSocketDisconnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApi
      RouteKey: $disconnect
      Target: !Sub 'integrations/${WebSocketDisconnectIntegration}'

  # --- WebSocket Default ---
  WebSocketDefaultFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'warmreach-ws-default-${Environment}'
      CodeUri: lambdas/websocket-default/
      Handler: lambda_function.lambda_handler
      Timeout: 29
      Role: !GetAtt WebSocketManageConnectionsRole.Arn
      Layers:
        - !Ref SharedPythonLayer
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref ProfilesTable
          LOG_LEVEL: INFO
          WEBSOCKET_ENDPOINT: !Sub 'https://${WebSocketApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}'

  WebSocketDefaultPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref WebSocketDefaultFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebSocketApi}/*/$default'

  WebSocketDefaultIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebSocketDefaultFunction.Arn}/invocations'

  WebSocketDefaultRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApi
      RouteKey: $default
      Target: !Sub 'integrations/${WebSocketDefaultIntegration}'

  # ==========================================================================
  # Command Dispatch (HTTP API routes for command lifecycle)
  # ==========================================================================
  CommandDispatchFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'warmreach-command-dispatch-${Environment}'
      CodeUri: lambdas/command-dispatch/
      Handler: lambda_function.lambda_handler
      Timeout: 10
      Role: !GetAtt WebSocketManageConnectionsRole.Arn
      Layers:
        - !Ref SharedPythonLayer
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref ProfilesTable
          LOG_LEVEL: INFO
          WEBSOCKET_ENDPOINT: !Sub 'https://${WebSocketApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}'
          ALLOWED_ORIGINS: !If
            - IncludeDevOriginsCondition
            - !Sub 'http://localhost:5173,http://localhost:3000${ProductionOrigins}'
            - !Ref ProductionOrigins
      Events:
        CreateCommand:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /commands
            Method: POST
        GetCommand:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /commands/{commandId}
            Method: GET
        CommandsOptions:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /commands
            Method: OPTIONS
            Auth:
              Authorizer: NONE
        CommandIdOptions:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /commands/{commandId}
            Method: OPTIONS
            Auth:
              Authorizer: NONE

  EdgeProcessingFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'warmreach-edge-processing-${Environment}'
      CodeUri: lambdas/edge-processing/
      Handler: lambda_function.lambda_handler
      Timeout: 60
      Environment:
        Variables:
          RAGSTACK_GRAPHQL_ENDPOINT: !If
            - DeployRAGStackCondition
            - !GetAtt RAGStackNestedStack.Outputs.GraphQLApiUrl
            - !Ref RagstackGraphqlEndpoint
          RAGSTACK_API_KEY: !If
            - DeployRAGStackCondition
            - !GetAtt RAGStackNestedStack.Outputs.GraphQLApiKey
            - !Ref RagstackApiKey
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ProfilesTable
      Events:
        EdgeApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /edges
            Method: POST
        EdgeOptionsApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /edges
            Method: OPTIONS
            Auth:
              Authorizer: NONE
        RagstackApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /ragstack
            Method: POST
        RagstackOptionsApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /ragstack
            Method: OPTIONS
            Auth:
              Authorizer: NONE

  DynamoDBApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'warmreach-dynamodb-api-${Environment}'
      CodeUri: lambdas/dynamodb-api/
      Handler: lambda_function.lambda_handler
      Environment:
        Variables:
          COGNITO_USER_POOL_ID: !Ref UserPool
          COGNITO_REGION: !Ref AWS::Region
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ProfilesTable
      Events:
        DynamoDBGet:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /dynamodb
            Method: GET
        DynamoDBPost:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /dynamodb
            Method: POST
        DynamoDBOptions:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /dynamodb
            Method: OPTIONS
            Auth:
              Authorizer: NONE
        ProfileGet:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /profiles
            Method: GET
        ProfilePost:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /profiles
            Method: POST
        ProfileOptions:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /profiles
            Method: OPTIONS
            Auth:
              Authorizer: NONE

  LLMFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'warmreach-llm-${Environment}'
      CodeUri: lambdas/llm/
      Handler: lambda_function.lambda_handler
      Timeout: 90
      MemorySize: 512
      Environment:
        Variables:
          OPENAI_API_KEY: !Ref OpenAIApiKey
          BEDROCK_MODEL_ID: !Ref BedrockModelId
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ProfilesTable
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource: !Sub 'arn:aws:bedrock:${AWS::Region}::foundation-model/*'
      Events:
        LLMApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /llm
            Method: POST
        LLMOptionsApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /llm
            Method: OPTIONS
            Auth:
              Authorizer: NONE



Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}'
  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref UserPool
  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref UserPoolClient
  DynamoDBTableName:
    Description: DynamoDB table name
    Value: !Ref ProfilesTable
  WebSocketApiUrl:
    Description: WebSocket API endpoint URL
    Value: !Sub 'wss://${WebSocketApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}'
  # RAGStack Outputs (only available when DeployRAGStack=true)
  RAGStackGraphQLEndpoint:
    Condition: DeployRAGStackCondition
    Description: RAGStack GraphQL API endpoint for semantic search
    Value: !GetAtt RAGStackNestedStack.Outputs.GraphQLApiUrl
  RAGStackDashboardUrl:
    Condition: DeployRAGStackCondition
    Description: RAGStack Dashboard URL for document management
    Value: !GetAtt RAGStackNestedStack.Outputs.UIUrl
